// Generated by Wrangler by running `wrangler types`

interface Env {
	CLIENT_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").ClientDurableObject>;
	TOPIC_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").TopicDurableObject>;
}
